name: README build

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - uses: actions/setup-node@v3
        name: Install Node.js
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2.2.2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Generate README file
        run: pnpm build

      # - uses: EndBug/add-and-commit@v9
      #   with:
      #     add: "."
      #     author_name: Nsttt
      #     author_email: nestor@nstlopez.com
      #     commit: --signoff
      #     message: "Readme Build"
      #     pull: "--rebase publisher master"
      #     tag_push: "publisher master"
      - name: Setup Git
        run: |
          # Setting up credentials
          git config http.sslVerify false
          git config user.name "Automated Publisher"
          git config user.email "actions@users.noreply.github.com"
          git remote add publisher https://github.com/Nsttt/Nsttt.git
      - name: Commit changes
        run: |
          # Add changes and commit
          git checkout master
          git add -A
          git commit -m "Automated publish" || exit 0
          git pull --rebase publisher master
          git push publisher master

